# Generated by Django 4.2.7 on 2023-11-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0002_remove_recognizedalphabet_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognizedalphabet',
            name='alphabet',
            field=models.CharField(max_length=100),
        ),
    ]
