# Generated by Django 4.2.7 on 2023-11-16 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0003_alter_recognizedalphabet_alphabet'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognizedalphabet',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recognizedalphabet',
            name='alphabet',
            field=models.CharField(max_length=1),
        ),
    ]
