# Generated by Django 4.2.7 on 2023-11-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0004_recognizedalphabet_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recognizedalphabet',
            name='timestamp',
        ),
    ]
