# Generated by Django 4.2.7 on 2023-11-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0005_remove_recognizedalphabet_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognizedSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('alphabet', models.CharField(max_length=255)),
            ],
        ),
    ]
