# Generated by Django 4.2.7 on 2023-11-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0006_recognizedsequence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecognizedSequence',
        ),
    ]
