# Generated by Django 4.2.7 on 2023-11-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0007_delete_recognizedsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognizedalphabet',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recognizedalphabet',
            name='alphabet',
            field=models.CharField(max_length=255),
        ),
    ]
