# Generated by Django 4.2.7 on 2023-11-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0008_recognizedalphabet_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognizedalphabet',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
